openapi: 3.0.3
info:
  title: Martlett API
  version: 0.0.1
  description: API contract used for OpenAPI code generation.

paths:
  /api/auth/register:
    $ref: "./paths/auth-register.yaml"
  /api/auth/token:
    $ref: "./paths/auth-token.yaml"
  /api/auth/refresh:
    $ref: "./paths/auth-refresh.yaml"
  /api/me:
    $ref: "./paths/users.yaml#/currentUserPath"
  /api/me/avatar:
    $ref: "./paths/users.yaml#/currentUserAvatarPath"
  /api/users/{username}:
    $ref: "./paths/users.yaml#/userByUsernamePath"
  /api/users/{username}/avatar:
    $ref: "./paths/users.yaml#/userAvatarPath"
  /api/users/{username}/repositories:
    $ref: "./paths/users.yaml#/userRepositoriesPath"
  /api/repositories:
    $ref: "./paths/repositories.yaml#/repositoriesPath"
  /api/repositories/{repositoryName}:
    $ref: "./paths/repositories.yaml#/repositoryByNamePath"
  /api/repositories/{username}/{repositoryName}:
    $ref: "./paths/repositories.yaml#/userRepositoryByNamePath"
  /api/repositories/{username}/{repositoryName}/branches:
    $ref: "./paths/repositories.yaml#/userRepositoryBranchesPath"
  /api/repositories/{username}/{repositoryName}/tree:
    $ref: "./paths/repositories.yaml#/userRepositoryTreePath"
  /api/repositories/{username}/{repositoryName}/blob:
    $ref: "./paths/repositories.yaml#/userRepositoryBlobPath"
  /api/repositories/{username}/{repositoryName}/blob/raw:
    $ref: "./paths/repositories.yaml#/userRepositoryRawBlobPath"
  /api/repositories/{username}/{repositoryName}/readme:
    $ref: "./paths/repositories.yaml#/userRepositoryReadmePath"
  /api/repositories/{username}/{repositoryName}/commits:
    $ref: "./paths/repositories.yaml#/userRepositoryCommitsPath"

components:
  responses:
    AuthenticationRequired:
      description: Authentication required
    AccessDenied:
      description: Access denied
    InvalidRequest:
      description: Invalid request
    UserNotFound:
      description: User not found
    RepositoryNotFound:
      description: Repository not found
    RepositoryContentNotFound:
      description: Repository content not found
    RepositoryAlreadyExists:
      description: Repository already exists
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
