name: martlett

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U martlett -d martlett"]
      interval: 5s
      timeout: 5s
      retries: 20

#  vault:
#    image: hashicorp/vault:1.19.0
#    container_name: martlett-vault
#    restart: unless-stopped
#    cap_add:
#      - IPC_LOCK
#    command: server
#    environment:
#      SKIP_CHOWN: "true"
#    ports:
#      - "127.0.0.1:8200:8200"
#    volumes:
#      - ./ops/vault/config:/vault/config:ro
#      - vault-data:/vault/file
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "vault status -address=http://127.0.0.1:8200 >/dev/null 2>&1; code=$$?; [ \"$$code\" -eq 0 ] || [ \"$$code\" -eq 2 ]"
#        ]
#      interval: 5s
#      timeout: 5s
#      retries: 20

  app:
    image: ghcr.io/elypsoeed/martlett:staging
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"


volumes:
  postgres-data:
  vault-data:
