spring:
  config:
    import: vault:///secret/martlett/app
  cloud:
    vault:
      enabled: true
      uri: http://127.0.0.1:8200
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_APPROLE_ROLE_ID}
        secret-id: ${VAULT_APPROLE_SECRET_ID}
      fail-fast: true