services:

  postgres:
    ports:
      - "127.0.0.1:5432:5432"

  app:
    image: ghcr.io/elypsoeed/martlett:staging
    environment:
      APP_FLYWAY_RERUN_MIGRATIONS: "true"
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-https://martlett.publicstatic.space}
