create table usrs (
    id bigint generated by default as identity primary key,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    username varchar(255) not null unique,
    registration_timestamp timestamp with time zone,
    sex varchar(16),
    age integer,
    city varchar(255),
    tg_contact varchar(255),
    email_contact varchar(255),
    place_of_work varchar(255),
    constraint chk_usrs_sex check (sex in ('MALE', 'FEMALE', 'OTHER'))
);

create table auth_users (
    user_id bigint primary key,
    username varchar(255) not null unique,
    password_hash varchar(255) not null,
    constraint fk_auth_users_user_id
        foreign key (user_id) references usrs (id) on delete cascade
);

create table auth_user_roles (
    user_id bigint not null,
    role varchar(32) not null,
    constraint pk_auth_user_roles primary key (user_id, role),
    constraint fk_auth_user_roles_user_id
        foreign key (user_id) references auth_users (user_id) on delete cascade,
    constraint chk_auth_user_roles_role check (role in ('USER', 'ADMIN'))
);
