create table hosted_repositories (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    name varchar(255) not null,
    storage_relative_path varchar(1024) not null unique,
    created_timestamp timestamp with time zone not null,
    constraint fk_hosted_repositories_owner_user_id
        foreign key (owner_user_id) references usrs (id) on delete cascade,
    constraint uq_hosted_repositories_owner_name unique (owner_user_id, name)
);
