create table repository_permissions (
    id bigint generated by default as identity primary key,
    repository_id bigint not null,
    subject_type varchar(32) not null,
    subject_id bigint not null,
    permission varchar(64) not null,
    constraint fk_repository_permissions_repository_id
        foreign key (repository_id) references git_repositories (id) on delete cascade,
    constraint uq_repository_permissions_subject
        unique (repository_id, subject_type, subject_id, permission)
);
