create table repository_roles (
    id bigint generated by default as identity primary key,
    repository_id bigint not null,
    subject_type varchar(32) not null,
    subject_id bigint not null,
    role varchar(64) not null,
    constraint fk_repository_roles_repository_id
        foreign key (repository_id) references git_repositories (id) on delete cascade,
    constraint uq_repository_roles_subject
        unique (repository_id, subject_type, subject_id, role)
);
